import dayjs from "dayjs";

import type {
  AvailabilityRequest,
  Booking,
  BookingDocument,
  DocumentKind,
  EmailLog,
  GuesthouseSnapshot,
  Room,
  SelectedPackage,
  UpdateRoomInput,
  UpsertBookingInput,
  UpsertDocumentInput
} from "../../shared/domain";
import {
  createDefaultLineItems,
  findDocumentForBooking,
  summarizeOccupancy
} from "../../shared/utils";

export function createAvailabilityDraft(): AvailabilityRequest {
  const start = dayjs().add(1, "day");
  const end = start.add(2, "day");

  return {
    checkIn: start.format("YYYY-MM-DD"),
    checkOut: end.format("YYYY-MM-DD"),
    guests: 2
  };
}

export function createRoomDraft(room: Room): UpdateRoomInput {
  return {
    id: room.id,
    rate: room.rate,
    status: room.status,
    packageOptions: room.packageOptions
  };
}

function defaultSelectedPackages(room: Room): SelectedPackage[] {
  return room.packageOptions
    .filter((option) => option.pricingMode !== "custom")
    .slice(0, 1)
    .map((option) => ({
      id: option.id,
      name: option.name,
      pricingMode: option.pricingMode,
      quantity: 1,
      unitPrice: option.price,
      totalPrice: option.price
    }));
}

export function createBookingDraft(room: Room): UpsertBookingInput {
  const checkIn = dayjs().add(2, "day");
  const checkOut = checkIn.add(2, "day");

  return {
    id: crypto.randomUUID(),
    guestName: "",
    guestEmail: "",
    guestPhone: "",
    roomId: room.id,
    source: "Direct",
    status: "pending",
    checkIn: checkIn.format("YYYY-MM-DD"),
    checkOut: checkOut.format("YYYY-MM-DD"),
    guests: 2,
    nightlyRate: room.rate,
    cleaningFee: 22,
    taxAmount: 18,
    discountAmount: 0,
    selectedPackages: defaultSelectedPackages(room),
    specialRequests: "",
    internalNotes: ""
  };
}

export function createDocumentDraft(
  snapshot: GuesthouseSnapshot,
  booking: Booking,
  kind: DocumentKind
): UpsertDocumentInput {
  const existing = findDocumentForBooking(snapshot.documents, booking.id, kind);
  const room = snapshot.rooms.find((entry) => entry.id === booking.roomId);

  if (existing) {
    return {
      id: existing.id,
      bookingId: existing.bookingId,
      kind: existing.kind,
      status: existing.status,
      recipientEmail: existing.recipientEmail,
      issueDate: existing.issueDate,
      dueDate: existing.dueDate,
      currency: existing.currency,
      note: existing.note,
      lineItems: existing.lineItems,
      taxAmount: existing.taxAmount,
      discountAmount: existing.discountAmount
    };
  }

  return {
    id: crypto.randomUUID(),
    bookingId: booking.id,
    kind,
    status: kind === "quotation" ? "draft" : "sent",
    recipientEmail: booking.guestEmail,
    issueDate: dayjs().format("YYYY-MM-DD"),
    dueDate: dayjs().add(kind === "quotation" ? 7 : 14, "day").format("YYYY-MM-DD"),
    currency: snapshot.profile.currency,
    note:
      kind === "quotation"
        ? "Quotation prepared directly from OmniHost."
        : "Invoice generated by OmniHost.",
    lineItems: createDefaultLineItems(booking, room),
    taxAmount: booking.taxAmount,
    discountAmount: booking.discountAmount
  };
}

export function buildRecentActivity(snapshot: GuesthouseSnapshot) {
  const bookingActivity = snapshot.bookings.slice(0, 4).map((booking) => ({
    id: `booking-${booking.id}`,
    label: `${booking.guestName} booking ${booking.status}`,
    timestamp: booking.updatedAt
  }));
  const documentActivity = snapshot.documents.slice(0, 4).map((document) => ({
    id: `document-${document.id}`,
    label: `${document.kind} ${document.documentNumber} ${document.status}`,
    timestamp: document.updatedAt
  }));
  const emailActivity = snapshot.emails.slice(0, 4).map((email) => ({
    id: `email-${email.id}`,
    label: `${email.kind} email ${email.status}`,
    timestamp: email.updatedAt
  }));

  return [...bookingActivity, ...documentActivity, ...emailActivity]
    .sort((left, right) => dayjs(right.timestamp).valueOf() - dayjs(left.timestamp).valueOf())
    .slice(0, 8);
}

export function buildHousekeeping(snapshot: GuesthouseSnapshot) {
  const today = dayjs().format("YYYY-MM-DD");

  return snapshot.bookings
    .filter((booking) => booking.checkOut <= today || booking.checkIn === today)
    .map((booking) => ({
      booking,
      room: snapshot.rooms.find((room) => room.id === booking.roomId),
      task:
        booking.checkIn === today
          ? "Arrival prep"
          : booking.status === "checked-out"
            ? "Turnover clean"
            : "Departure follow-up"
    }));
}

export function buildGuestProfiles(bookings: Booking[]) {
  const map = new Map<
    string,
    { name: string; email: string; phone: string; stays: number; revenue: number; lastStay: string }
  >();

  for (const booking of bookings) {
    const current = map.get(booking.guestEmail) ?? {
      name: booking.guestName,
      email: booking.guestEmail,
      phone: booking.guestPhone,
      stays: 0,
      revenue: 0,
      lastStay: booking.checkOut
    };

    current.stays += 1;
    current.revenue += booking.totalAmount;
    current.lastStay = current.lastStay > booking.checkOut ? current.lastStay : booking.checkOut;
    map.set(booking.guestEmail, current);
  }

  return [...map.values()].sort((left, right) => right.revenue - left.revenue);
}

export function buildFinanceSnapshot(snapshot: GuesthouseSnapshot) {
  const invoices = snapshot.documents.filter((document) => document.kind === "invoice");
  const quotations = snapshot.documents.filter((document) => document.kind === "quotation");

  return {
    invoicesRaised: invoices.reduce((sum, invoice) => sum + invoice.totalAmount, 0),
    outstanding: invoices
      .filter((invoice) => invoice.status !== "paid")
      .reduce((sum, invoice) => sum + invoice.totalAmount, 0),
    quotationsOpen: quotations.filter((quotation) => quotation.status !== "accepted").length,
    sentEmails: snapshot.emails.filter((email) => email.status === "sent").length
  };
}

export function buildReporting(snapshot: GuesthouseSnapshot) {
  const occupancy = summarizeOccupancy(snapshot.rooms, snapshot.bookings);
  const sourceMap = new Map<string, number>();

  for (const booking of snapshot.bookings) {
    sourceMap.set(booking.source, (sourceMap.get(booking.source) ?? 0) + 1);
  }

  const packageUptake = snapshot.bookings.reduce((sum, booking) => sum + booking.selectedPackages.length, 0);

  return {
    occupancy,
    bookingSources: [...sourceMap.entries()],
    packageUptake
  };
}

export function buildControlSummary(snapshot: GuesthouseSnapshot, queueDepth: number, emails: EmailLog[]) {
  return {
    queueDepth,
    auditEvents: emails.length + snapshot.documents.length + snapshot.bookings.length,
    authMode: "Password hashing + session token",
    providerStatus: "Provider-ready"
  };
}

